### ISSUE TITLE
Support for reading?

### ISSUE THREAD

**Issue by cstrahan** [david-res/ILI948x_t4_mm#2]
Hi @david-res -- I was curious if you have some working code for reading data. I see the declaration for `SglBeatRD_nPrm_8`, but I don't I know if its definition is implemented/checked into git.

**Comment by cstrahan** [comment]
FWIW, I found NXP's LCD driver here: https://github.com/ARMmbed/mbed-os/blob/5c8e60f80be658d65fbb78a70514d83c23d60a7a/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexio_mculcd.c

Following that, I managed to get reading to work :)



https://www.nxp.com/docs/en/application-note/AN12822.pdf

Also, found these resources to help:

- [Understanding FlexIO](https://community.nxp.com/t5/Kinetis-Microcontrollers/Understanding-FlexIO/ta-p/1115419)
- [i.MX RT1060 Processor Reference Manual](https://www.pjrc.com/teensy/IMXRT1060RM_rev3.pdf)
- [AN12822 - Emulating 8080 Bus with the FlexIO on RT1050](https://www.nxp.com/docs/en/application-note/AN12822.pdf)

Thanks again for your work!

**Comment by david-res** [comment]
@cstrahan great work!
I used AN12822  and a 1050 8080 demo code pack to build this library with the help of some forum members.
I did add the declaration for the read function but didn't find the time to get to it.

Would you like to do a PR so that I can merge your code with the library?

**Comment by david-res** [comment]
@cstrahan just checking if you saw the comment above?

**Comment by cstrahan** [comment]
Hi @david-res!

Sorry, missed your messages earlier. I've been pretty swamped looking for a new job, after losing mine to layoffs (haven't had any time for my pet projects either :smiling_face_with_tear:).

> Would you like to do a PR so that I can merge your code with the library?

The code I mentioned earlier was written in Rust, and the organization/approach is quite different here (as one example, I have more fine grained state management of the FlexIO, instead of globally disabling/enabling FlexIO -- inspired by NXP's libraries).

When I can spare a moment, I'll see if I can re-implement reads in a way suitable for inclusion in this library (i.e. in C++ and fitting the existing patterns/design). Shouldn't be too much work -- I just need to carve out the time, and have sufficient will power, haha.

**Comment by david-res** [comment]
@cstrahan I was in your shoes 8 months ago! I feel you on that!

I think I have managed to get most of the read code implemented, I just need to test it (haven't had time for that)
As soon as I have implemented it I will close this issue.

By the way I have created a new library that does the same thing for the T4.1 without the DMA transfers (https://github.com/david-res/ILI948x_t41_p)

Good luck with the job hunt! I hope you find a company/role that is a good fit for you!

**Comment by david-res** [comment]
@cstrahan can you share the register config for reading?
I've been at this for two days with the following config and can't get any data to come in:

`
FASTRUN void ILI948x_t4_mm::FlexIO_Config_SnglBeat_Read()
{
  
    p->CTRL &= ~FLEXIO_CTRL_FLEXEN;
    p->CTRL |= FLEXIO_CTRL_SWRST;
    p->CTRL &= ~FLEXIO_CTRL_SWRST;

    gpioRead();

    /* Configure the shifters */
    p->SHIFTCFG[3] = 
        //FLEXIO_SHIFTCFG_INSRC                                                  /* Shifter input */
        FLEXIO_SHIFTCFG_SSTOP(0)                                              /* Shifter stop bit disabled */
       | FLEXIO_SHIFTCFG_SSTART(0)                                             /* Shifter start bit disabled and loading data on enabled */
       | FLEXIO_SHIFTCFG_PWIDTH(7);                                            /* Bus width */
     
    p->SHIFTCTL[3] = 
        FLEXIO_SHIFTCTL_TIMSEL(1)                                              /* Shifter's assigned timer index */
      | FLEXIO_SHIFTCTL_TIMPOL*(0)                                             /* Shift on posedge of shift clock */
      | FLEXIO_SHIFTCTL_PINCFG(0)                                              /* Shifter's pin configured as input */
      | FLEXIO_SHIFTCTL_PINSEL(4)                                              /* Shifter's pin start index */
      | FLEXIO_SHIFTCTL_PINPOL*(0)                                             /* Shifter's pin active high */
      | FLEXIO_SHIFTCTL_SMOD(1);                                               /* Shifter mode as recieve */

    /* Configure the timer for shift clock */
    p->TIMCMP[1] = 
        (((1 * 2) - 1) << 8)                                                   /* TIMCMP[15:8] = number of beats x 2 – 1 */
      | (((30)/2) - 1);                                                        /* TIMCMP[7:0] = baud rate divider / 2 – 1 ::: 30 = 8Mhz with current controller speed */
    
    p->TIMCFG[1] = 
        FLEXIO_TIMCFG_TIMOUT(0)                                                /* Timer output logic one when enabled and not affected by reset */
      | FLEXIO_TIMCFG_TIMDEC(0)                                                /* Timer decrement on FlexIO clock, shift clock equals timer output */
      | FLEXIO_TIMCFG_TIMRST(0)                                                /* Timer never reset */
      | FLEXIO_TIMCFG_TIMDIS(2)                                                /* Timer disabled on timer compare */
      | FLEXIO_TIMCFG_TIMENA(2)                                                /* Timer enabled on trigger high */
      | FLEXIO_TIMCFG_TSTOP(0)                                                 /* Timer stop bit disabled */
      | FLEXIO_TIMCFG_TSTART*(0);                                              /* Timer start bit disabled */
    
    p->TIMCTL[1] = 
        FLEXIO_TIMCTL_TRGSEL((((3) << 2) | 1))                                 /* Timer trigger selected as shifter's status flag */
      | FLEXIO_TIMCTL_TRGPOL*(1)                                               /* Timer trigger polarity as active low */
      | FLEXIO_TIMCTL_TRGSRC*(1)                                               /* Timer trigger source as internal */
      | FLEXIO_TIMCTL_PINCFG(3)                                                /* Timer' pin configured as output */
      | FLEXIO_TIMCTL_PINSEL(1)                                                /* Timer' pin index: WR pin */
      | FLEXIO_TIMCTL_PINPOL*(1)                                               /* Timer' pin active low */
      | FLEXIO_TIMCTL_TIMOD(1);                                                /* Timer mode as dual 8-bit counters baud/bit */

  
    /* Enable FlexIO */
   p->CTRL |= FLEXIO_CTRL_FLEXEN;      

}
`

gpioRead:
`
FASTRUN void ILI948x_t4_mm::gpioRead(){
  pFlex->setIOPinToFlexMode(12);
  pinMode(10, OUTPUT);
  digitalWriteFast(10, HIGH);
}
`

readCommand:
`
FASTRUN uint8_t ILI948x_t4_mm::readCommand(uint8_t const cmd){
  while(WR_DMATransferDone == false)
  {
    //Wait for any DMA transfers to complete
  }

    FlexIO_Config_SnglBeat();
    DCLow();

    /* Write command index */
    p->SHIFTBUF[0] = cmd;

    /*Wait for transfer to be completed */
    while(0 == (p->SHIFTSTAT & (1 << 0)))
    {
    }
    while(0 == (p->TIMSTAT & (1 << 0)))
            {  
            }

    /* De-assert RS pin */
    microSecondDelay();
    DCHigh();
    FlexIO_Clear_Config_SnglBeat();
    FlexIO_Config_SnglBeat_Read();

    uint32_t dummy;
    uint32_t data = 0;

    while (0 == (p->SHIFTSTAT & (1 << 3)))
        {
        }
    dummy = p->SHIFTBUF[3];

    while (0 == (p->SHIFTSTAT & (1 << 3)))
        {
        }
    data = p->SHIFTBUF[3];

    Serial.printf("Dummy 0x%x, data 0x%x\n", dummy, data);
    
    
    //Set FlexIO back to Write mode
    FlexIO_Config_SnglBeat();
  return data;
};`

Does anything look off here?

**Comment by david-res** [comment]
I got this working! thanks to the Application notes that you linked to (I has actually used it when putting this library together)

FLEXIO_SHIFTCTL_TIMPOL bit needs to be enabled to shift on negative edge
FLEXIO_TIMCFG_TSTOP time stop bit needs to be enabled

And then to read the data in the right order I read from SHIFTBUSBYS for a half word swap.

Closing this issue
